// Generated by gencpp from file planner_semantic_msgs/SemanticPoint.msg
// DO NOT EDIT!


#ifndef PLANNER_SEMANTIC_MSGS_MESSAGE_SEMANTICPOINT_H
#define PLANNER_SEMANTIC_MSGS_MESSAGE_SEMANTICPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <planner_semantic_msgs/SemanticClass.h>
#include <std_msgs/String.h>
#include <geometry_msgs/Point32.h>

namespace planner_semantic_msgs
{
template <class ContainerAllocator>
struct SemanticPoint_
{
  typedef SemanticPoint_<ContainerAllocator> Type;

  SemanticPoint_()
    : header()
    , type()
    , description()
    , point()  {
    }
  SemanticPoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , description(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::planner_semantic_msgs::SemanticClass_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef  ::std_msgs::String_<ContainerAllocator>  _description_type;
  _description_type description;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> const> ConstPtr;

}; // struct SemanticPoint_

typedef ::planner_semantic_msgs::SemanticPoint_<std::allocator<void> > SemanticPoint;

typedef boost::shared_ptr< ::planner_semantic_msgs::SemanticPoint > SemanticPointPtr;
typedef boost::shared_ptr< ::planner_semantic_msgs::SemanticPoint const> SemanticPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator1> & lhs, const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.description == rhs.description &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator1> & lhs, const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_semantic_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4e8d6f91194ca358a218194b2f66232";
  }

  static const char* value(const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4e8d6f91194ca35ULL;
  static const uint64_t static_value2 = 0x8a218194b2f66232ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_semantic_msgs/SemanticPoint";
  }

  static const char* value(const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represent semantics as a 3D point\n"
"std_msgs/Header header\n"
"\n"
"# Class of semantics\n"
"planner_semantic_msgs/SemanticClass type\n"
"\n"
"# Further info if needed\n"
"std_msgs/String description\n"
"\n"
"# Coordinate of the semantics\n"
"geometry_msgs/Point32 point\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: planner_semantic_msgs/SemanticClass\n"
"# Semantic classes\n"
"int32 kNone = 0\n"
"int32 kStaircase = 1\n"
"int32 kDoor = 2\n"
"\n"
"# Can only choose one of the above\n"
"int32 value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.description);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SemanticPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_semantic_msgs::SemanticPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer< ::planner_semantic_msgs::SemanticClass_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "description: ";
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.description);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point: ";
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_SEMANTIC_MSGS_MESSAGE_SEMANTICPOINT_H
