// Generated by gencpp from file planner_msgs/pathFollowerActionResult.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONRESULT_H
#define PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct pathFollowerActionResult_
{
  typedef pathFollowerActionResult_<ContainerAllocator> Type;

  pathFollowerActionResult_()
    : success(false)  {
    }
  pathFollowerActionResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct pathFollowerActionResult_

typedef ::planner_msgs::pathFollowerActionResult_<std::allocator<void> > pathFollowerActionResult;

typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionResult > pathFollowerActionResultPtr;
typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionResult const> pathFollowerActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator1> & lhs, const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator1> & lhs, const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/pathFollowerActionResult";
  }

  static const char* value(const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathFollowerActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::pathFollowerActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::pathFollowerActionResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONRESULT_H
