// Generated by gencpp from file planner_msgs/pathFollowerActionGoal.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONGOAL_H
#define PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct pathFollowerActionGoal_
{
  typedef pathFollowerActionGoal_<ContainerAllocator> Type;

  pathFollowerActionGoal_()
    : path()  {
    }
  pathFollowerActionGoal_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pathFollowerActionGoal_

typedef ::planner_msgs::pathFollowerActionGoal_<std::allocator<void> > pathFollowerActionGoal;

typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionGoal > pathFollowerActionGoalPtr;
typedef boost::shared_ptr< ::planner_msgs::pathFollowerActionGoal const> pathFollowerActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator1> & lhs, const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator1> & lhs, const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fde6cfd88a2e9547561cecdb69ccf8c";
  }

  static const char* value(const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fde6cfd88a2e954ULL;
  static const uint64_t static_value2 = 0x7561cecdb69ccf8cULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/pathFollowerActionGoal";
  }

  static const char* value(const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"geometry_msgs/PoseStamped[] path\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathFollowerActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::pathFollowerActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    if (v.path.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.path[i]);
    }
    if (v.path.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PATHFOLLOWERACTIONGOAL_H
