// Generated by gencpp from file planner_msgs/pci_homing_trigger.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PCI_HOMING_TRIGGER_H
#define PLANNER_MSGS_MESSAGE_PCI_HOMING_TRIGGER_H

#include <ros/service_traits.h>


#include <planner_msgs/pci_homing_triggerRequest.h>
#include <planner_msgs/pci_homing_triggerResponse.h>


namespace planner_msgs
{

struct pci_homing_trigger
{

typedef pci_homing_triggerRequest Request;
typedef pci_homing_triggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pci_homing_trigger
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::pci_homing_trigger > {
  static const char* value()
  {
    return "9ac7156ead9cf693072fe52aad9e8e2c";
  }

  static const char* value(const ::planner_msgs::pci_homing_trigger&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::pci_homing_trigger > {
  static const char* value()
  {
    return "planner_msgs/pci_homing_trigger";
  }

  static const char* value(const ::planner_msgs::pci_homing_trigger&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::pci_homing_triggerRequest> should match
// service_traits::MD5Sum< ::planner_msgs::pci_homing_trigger >
template<>
struct MD5Sum< ::planner_msgs::pci_homing_triggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_homing_trigger >::value();
  }
  static const char* value(const ::planner_msgs::pci_homing_triggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_homing_triggerRequest> should match
// service_traits::DataType< ::planner_msgs::pci_homing_trigger >
template<>
struct DataType< ::planner_msgs::pci_homing_triggerRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_homing_trigger >::value();
  }
  static const char* value(const ::planner_msgs::pci_homing_triggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::pci_homing_triggerResponse> should match
// service_traits::MD5Sum< ::planner_msgs::pci_homing_trigger >
template<>
struct MD5Sum< ::planner_msgs::pci_homing_triggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_homing_trigger >::value();
  }
  static const char* value(const ::planner_msgs::pci_homing_triggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_homing_triggerResponse> should match
// service_traits::DataType< ::planner_msgs::pci_homing_trigger >
template<>
struct DataType< ::planner_msgs::pci_homing_triggerResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_homing_trigger >::value();
  }
  static const char* value(const ::planner_msgs::pci_homing_triggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PCI_HOMING_TRIGGER_H
