// Generated by gencpp from file planner_msgs/pci_initialization.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PCI_INITIALIZATION_H
#define PLANNER_MSGS_MESSAGE_PCI_INITIALIZATION_H

#include <ros/service_traits.h>


#include <planner_msgs/pci_initializationRequest.h>
#include <planner_msgs/pci_initializationResponse.h>


namespace planner_msgs
{

struct pci_initialization
{

typedef pci_initializationRequest Request;
typedef pci_initializationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pci_initialization
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::pci_initialization > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::planner_msgs::pci_initialization&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::pci_initialization > {
  static const char* value()
  {
    return "planner_msgs/pci_initialization";
  }

  static const char* value(const ::planner_msgs::pci_initialization&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::pci_initializationRequest> should match
// service_traits::MD5Sum< ::planner_msgs::pci_initialization >
template<>
struct MD5Sum< ::planner_msgs::pci_initializationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_initialization >::value();
  }
  static const char* value(const ::planner_msgs::pci_initializationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_initializationRequest> should match
// service_traits::DataType< ::planner_msgs::pci_initialization >
template<>
struct DataType< ::planner_msgs::pci_initializationRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_initialization >::value();
  }
  static const char* value(const ::planner_msgs::pci_initializationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::pci_initializationResponse> should match
// service_traits::MD5Sum< ::planner_msgs::pci_initialization >
template<>
struct MD5Sum< ::planner_msgs::pci_initializationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_initialization >::value();
  }
  static const char* value(const ::planner_msgs::pci_initializationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_initializationResponse> should match
// service_traits::DataType< ::planner_msgs::pci_initialization >
template<>
struct DataType< ::planner_msgs::pci_initializationResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_initialization >::value();
  }
  static const char* value(const ::planner_msgs::pci_initializationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PCI_INITIALIZATION_H
