// Generated by gencpp from file planner_msgs/pci_searchRequest.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PCI_SEARCHREQUEST_H
#define PLANNER_MSGS_MESSAGE_PCI_SEARCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct pci_searchRequest_
{
  typedef pci_searchRequest_<ContainerAllocator> Type;

  pci_searchRequest_()
    : header()
    , use_current_state(false)
    , not_exe_path(false)
    , bound_mode(0)  {
    }
  pci_searchRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , use_current_state(false)
    , not_exe_path(false)
    , bound_mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _use_current_state_type;
  _use_current_state_type use_current_state;

   typedef uint8_t _not_exe_path_type;
  _not_exe_path_type not_exe_path;

   typedef int32_t _bound_mode_type;
  _bound_mode_type bound_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kExtendedBound)
  #undef kExtendedBound
#endif
#if defined(_WIN32) && defined(kRelaxedBound)
  #undef kRelaxedBound
#endif
#if defined(_WIN32) && defined(kMinBound)
  #undef kMinBound
#endif
#if defined(_WIN32) && defined(kExactBound)
  #undef kExactBound
#endif
#if defined(_WIN32) && defined(kNoBound)
  #undef kNoBound
#endif

  enum {
    kExtendedBound = 0,
    kRelaxedBound = 1,
    kMinBound = 2,
    kExactBound = 3,
    kNoBound = 4,
  };


  typedef boost::shared_ptr< ::planner_msgs::pci_searchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::pci_searchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pci_searchRequest_

typedef ::planner_msgs::pci_searchRequest_<std::allocator<void> > pci_searchRequest;

typedef boost::shared_ptr< ::planner_msgs::pci_searchRequest > pci_searchRequestPtr;
typedef boost::shared_ptr< ::planner_msgs::pci_searchRequest const> pci_searchRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::pci_searchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::pci_searchRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::pci_searchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.use_current_state == rhs.use_current_state &&
    lhs.not_exe_path == rhs.not_exe_path &&
    lhs.bound_mode == rhs.bound_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::pci_searchRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::pci_searchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pci_searchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pci_searchRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pci_searchRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1853bf2c89b9dd526853f80fd427e36f";
  }

  static const char* value(const ::planner_msgs::pci_searchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1853bf2c89b9dd52ULL;
  static const uint64_t static_value2 = 0x6853f80fd427e36fULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/pci_searchRequest";
  }

  static const char* value(const ::planner_msgs::pci_searchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request the planning through the planner control interface node.\n"
"Header header\n"
"# Set True if want to set source pose at current robot's state;\n"
"# otherwise, get from inter=active marker\n"
"bool use_current_state\n"
"bool not_exe_path\n"
"\n"
"# Set the bound mode of the robot to use in planner.\n"
"# Use extension to actual size. (default)\n"
"int32 kExtendedBound = 0\n"
"int32 kRelaxedBound = 1\n"
"int32 kMinBound = 2\n"
"int32 kExactBound = 3\n"
"int32 kNoBound = 4\n"
"# Can only be used with one of above values. Check Params/BoundModeType for more details.\n"
"int32 bound_mode\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::planner_msgs::pci_searchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.use_current_state);
      stream.next(m.not_exe_path);
      stream.next(m.bound_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pci_searchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::pci_searchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::pci_searchRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_current_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_current_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "not_exe_path: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.not_exe_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bound_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bound_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PCI_SEARCHREQUEST_H
