// Generated by gencpp from file planner_msgs/pci_globalRequest.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PCI_GLOBALREQUEST_H
#define PLANNER_MSGS_MESSAGE_PCI_GLOBALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct pci_globalRequest_
{
  typedef pci_globalRequest_<ContainerAllocator> Type;

  pci_globalRequest_()
    : not_exe_path(false)
    , set_auto(false)
    , bound_mode(0)
    , vel_max(0.0)
    , id(0)
    , not_check_frontier(false)
    , ignore_time(false)  {
    }
  pci_globalRequest_(const ContainerAllocator& _alloc)
    : not_exe_path(false)
    , set_auto(false)
    , bound_mode(0)
    , vel_max(0.0)
    , id(0)
    , not_check_frontier(false)
    , ignore_time(false)  {
  (void)_alloc;
    }



   typedef uint8_t _not_exe_path_type;
  _not_exe_path_type not_exe_path;

   typedef uint8_t _set_auto_type;
  _set_auto_type set_auto;

   typedef uint8_t _bound_mode_type;
  _bound_mode_type bound_mode;

   typedef float _vel_max_type;
  _vel_max_type vel_max;

   typedef int32_t _id_type;
  _id_type id;

   typedef uint8_t _not_check_frontier_type;
  _not_check_frontier_type not_check_frontier;

   typedef uint8_t _ignore_time_type;
  _ignore_time_type ignore_time;





  typedef boost::shared_ptr< ::planner_msgs::pci_globalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::pci_globalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pci_globalRequest_

typedef ::planner_msgs::pci_globalRequest_<std::allocator<void> > pci_globalRequest;

typedef boost::shared_ptr< ::planner_msgs::pci_globalRequest > pci_globalRequestPtr;
typedef boost::shared_ptr< ::planner_msgs::pci_globalRequest const> pci_globalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::pci_globalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::pci_globalRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::pci_globalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.not_exe_path == rhs.not_exe_path &&
    lhs.set_auto == rhs.set_auto &&
    lhs.bound_mode == rhs.bound_mode &&
    lhs.vel_max == rhs.vel_max &&
    lhs.id == rhs.id &&
    lhs.not_check_frontier == rhs.not_check_frontier &&
    lhs.ignore_time == rhs.ignore_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::pci_globalRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::pci_globalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::pci_globalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::pci_globalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::pci_globalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b7aecbe90c397a53b27664f48377146";
  }

  static const char* value(const ::planner_msgs::pci_globalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b7aecbe90c397a5ULL;
  static const uint64_t static_value2 = 0x3b27664f48377146ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/pci_globalRequest";
  }

  static const char* value(const ::planner_msgs::pci_globalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request the planning through the planner control interface node.\n"
"\n"
"## Params for planner-control-interface\n"
"# Set not_exe_path to true if don't want the robot to execute the path.\n"
"bool not_exe_path\n"
"# Set set_auto to true to change to auto mode and vice versa.\n"
"bool set_auto\n"
"uint8 bound_mode\n"
"# Max velocity allowed.\n"
"float32 vel_max\n"
"\n"
"## Params for planner\n"
"# id of the frontier:\n"
"# --> default is 0: auto-select the best frontier.\n"
"# --> other than 0: manual select with feasibility check.\n"
"int32 id\n"
"# Don't check for frontier properties (e.g. leaf vertex, gain, ...).\n"
"# This could be used to find a path to any vertex in the graph.\n"
"bool not_check_frontier\n"
"# Force the planner to provide the path regardless the time budget.\n"
"bool ignore_time\n"
;
  }

  static const char* value(const ::planner_msgs::pci_globalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.not_exe_path);
      stream.next(m.set_auto);
      stream.next(m.bound_mode);
      stream.next(m.vel_max);
      stream.next(m.id);
      stream.next(m.not_check_frontier);
      stream.next(m.ignore_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pci_globalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::pci_globalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::pci_globalRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "not_exe_path: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.not_exe_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "set_auto: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_auto);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bound_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bound_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_max: ";
    Printer<float>::stream(s, indent + "  ", v.vel_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "not_check_frontier: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.not_check_frontier);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ignore_time: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ignore_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PCI_GLOBALREQUEST_H
