// Generated by gencpp from file planner_msgs/pci_stop.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PCI_STOP_H
#define PLANNER_MSGS_MESSAGE_PCI_STOP_H

#include <ros/service_traits.h>


#include <planner_msgs/pci_stopRequest.h>
#include <planner_msgs/pci_stopResponse.h>


namespace planner_msgs
{

struct pci_stop
{

typedef pci_stopRequest Request;
typedef pci_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pci_stop
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::pci_stop > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::planner_msgs::pci_stop&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::pci_stop > {
  static const char* value()
  {
    return "planner_msgs/pci_stop";
  }

  static const char* value(const ::planner_msgs::pci_stop&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::pci_stopRequest> should match
// service_traits::MD5Sum< ::planner_msgs::pci_stop >
template<>
struct MD5Sum< ::planner_msgs::pci_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_stop >::value();
  }
  static const char* value(const ::planner_msgs::pci_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_stopRequest> should match
// service_traits::DataType< ::planner_msgs::pci_stop >
template<>
struct DataType< ::planner_msgs::pci_stopRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_stop >::value();
  }
  static const char* value(const ::planner_msgs::pci_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::pci_stopResponse> should match
// service_traits::MD5Sum< ::planner_msgs::pci_stop >
template<>
struct MD5Sum< ::planner_msgs::pci_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::pci_stop >::value();
  }
  static const char* value(const ::planner_msgs::pci_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::pci_stopResponse> should match
// service_traits::DataType< ::planner_msgs::pci_stop >
template<>
struct DataType< ::planner_msgs::pci_stopResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::pci_stop >::value();
  }
  static const char* value(const ::planner_msgs::pci_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PCI_STOP_H
