// Generated by gencpp from file planner_msgs/planner_global.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_GLOBAL_H
#define PLANNER_MSGS_MESSAGE_PLANNER_GLOBAL_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_globalRequest.h>
#include <planner_msgs/planner_globalResponse.h>


namespace planner_msgs
{

struct planner_global
{

typedef planner_globalRequest Request;
typedef planner_globalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_global
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_global > {
  static const char* value()
  {
    return "3275d6e0291e4113fe8f0b4224d6de5a";
  }

  static const char* value(const ::planner_msgs::planner_global&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_global > {
  static const char* value()
  {
    return "planner_msgs/planner_global";
  }

  static const char* value(const ::planner_msgs::planner_global&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_globalRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_global >
template<>
struct MD5Sum< ::planner_msgs::planner_globalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_global >::value();
  }
  static const char* value(const ::planner_msgs::planner_globalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_globalRequest> should match
// service_traits::DataType< ::planner_msgs::planner_global >
template<>
struct DataType< ::planner_msgs::planner_globalRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_global >::value();
  }
  static const char* value(const ::planner_msgs::planner_globalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_globalResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_global >
template<>
struct MD5Sum< ::planner_msgs::planner_globalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_global >::value();
  }
  static const char* value(const ::planner_msgs::planner_globalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_globalResponse> should match
// service_traits::DataType< ::planner_msgs::planner_global >
template<>
struct DataType< ::planner_msgs::planner_globalResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_global >::value();
  }
  static const char* value(const ::planner_msgs::planner_globalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_GLOBAL_H
