// Generated by gencpp from file planner_msgs/planner_set_global_bound.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_SET_GLOBAL_BOUND_H
#define PLANNER_MSGS_MESSAGE_PLANNER_SET_GLOBAL_BOUND_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_set_global_boundRequest.h>
#include <planner_msgs/planner_set_global_boundResponse.h>


namespace planner_msgs
{

struct planner_set_global_bound
{

typedef planner_set_global_boundRequest Request;
typedef planner_set_global_boundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_set_global_bound
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_set_global_bound > {
  static const char* value()
  {
    return "1aed38fc3ce6d17635872f522b7dea8f";
  }

  static const char* value(const ::planner_msgs::planner_set_global_bound&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_set_global_bound > {
  static const char* value()
  {
    return "planner_msgs/planner_set_global_bound";
  }

  static const char* value(const ::planner_msgs::planner_set_global_bound&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_set_global_boundRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_set_global_bound >
template<>
struct MD5Sum< ::planner_msgs::planner_set_global_boundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_set_global_bound >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_global_boundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_set_global_boundRequest> should match
// service_traits::DataType< ::planner_msgs::planner_set_global_bound >
template<>
struct DataType< ::planner_msgs::planner_set_global_boundRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_set_global_bound >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_global_boundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_set_global_boundResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_set_global_bound >
template<>
struct MD5Sum< ::planner_msgs::planner_set_global_boundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_set_global_bound >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_global_boundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_set_global_boundResponse> should match
// service_traits::DataType< ::planner_msgs::planner_set_global_bound >
template<>
struct DataType< ::planner_msgs::planner_set_global_boundResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_set_global_bound >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_global_boundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_SET_GLOBAL_BOUND_H
