// Generated by gencpp from file planner_msgs/planner_go_to_waypoint.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_GO_TO_WAYPOINT_H
#define PLANNER_MSGS_MESSAGE_PLANNER_GO_TO_WAYPOINT_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_go_to_waypointRequest.h>
#include <planner_msgs/planner_go_to_waypointResponse.h>


namespace planner_msgs
{

struct planner_go_to_waypoint
{

typedef planner_go_to_waypointRequest Request;
typedef planner_go_to_waypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_go_to_waypoint
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_go_to_waypoint > {
  static const char* value()
  {
    return "a26081f4c02132c8e0c868df86f2d5fe";
  }

  static const char* value(const ::planner_msgs::planner_go_to_waypoint&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_go_to_waypoint > {
  static const char* value()
  {
    return "planner_msgs/planner_go_to_waypoint";
  }

  static const char* value(const ::planner_msgs::planner_go_to_waypoint&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_go_to_waypointRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_go_to_waypoint >
template<>
struct MD5Sum< ::planner_msgs::planner_go_to_waypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_go_to_waypoint >::value();
  }
  static const char* value(const ::planner_msgs::planner_go_to_waypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_go_to_waypointRequest> should match
// service_traits::DataType< ::planner_msgs::planner_go_to_waypoint >
template<>
struct DataType< ::planner_msgs::planner_go_to_waypointRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_go_to_waypoint >::value();
  }
  static const char* value(const ::planner_msgs::planner_go_to_waypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_go_to_waypointResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_go_to_waypoint >
template<>
struct MD5Sum< ::planner_msgs::planner_go_to_waypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_go_to_waypoint >::value();
  }
  static const char* value(const ::planner_msgs::planner_go_to_waypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_go_to_waypointResponse> should match
// service_traits::DataType< ::planner_msgs::planner_go_to_waypoint >
template<>
struct DataType< ::planner_msgs::planner_go_to_waypointResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_go_to_waypoint >::value();
  }
  static const char* value(const ::planner_msgs::planner_go_to_waypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_GO_TO_WAYPOINT_H
