// Generated by gencpp from file planner_msgs/planner_request_path.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_REQUEST_PATH_H
#define PLANNER_MSGS_MESSAGE_PLANNER_REQUEST_PATH_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_request_pathRequest.h>
#include <planner_msgs/planner_request_pathResponse.h>


namespace planner_msgs
{

struct planner_request_path
{

typedef planner_request_pathRequest Request;
typedef planner_request_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_request_path
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_request_path > {
  static const char* value()
  {
    return "1dad867088c8c204d2077d3355d04150";
  }

  static const char* value(const ::planner_msgs::planner_request_path&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_request_path > {
  static const char* value()
  {
    return "planner_msgs/planner_request_path";
  }

  static const char* value(const ::planner_msgs::planner_request_path&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_request_pathRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_request_path >
template<>
struct MD5Sum< ::planner_msgs::planner_request_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_request_path >::value();
  }
  static const char* value(const ::planner_msgs::planner_request_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_request_pathRequest> should match
// service_traits::DataType< ::planner_msgs::planner_request_path >
template<>
struct DataType< ::planner_msgs::planner_request_pathRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_request_path >::value();
  }
  static const char* value(const ::planner_msgs::planner_request_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_request_pathResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_request_path >
template<>
struct MD5Sum< ::planner_msgs::planner_request_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_request_path >::value();
  }
  static const char* value(const ::planner_msgs::planner_request_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_request_pathResponse> should match
// service_traits::DataType< ::planner_msgs::planner_request_path >
template<>
struct DataType< ::planner_msgs::planner_request_pathResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_request_path >::value();
  }
  static const char* value(const ::planner_msgs::planner_request_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_REQUEST_PATH_H
