// Generated by gencpp from file planner_msgs/planner_homing.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_HOMING_H
#define PLANNER_MSGS_MESSAGE_PLANNER_HOMING_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_homingRequest.h>
#include <planner_msgs/planner_homingResponse.h>


namespace planner_msgs
{

struct planner_homing
{

typedef planner_homingRequest Request;
typedef planner_homingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_homing
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_homing > {
  static const char* value()
  {
    return "0e9a67b6e01ddd6d303ae107f62349a1";
  }

  static const char* value(const ::planner_msgs::planner_homing&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_homing > {
  static const char* value()
  {
    return "planner_msgs/planner_homing";
  }

  static const char* value(const ::planner_msgs::planner_homing&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_homingRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_homing >
template<>
struct MD5Sum< ::planner_msgs::planner_homingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_homing >::value();
  }
  static const char* value(const ::planner_msgs::planner_homingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_homingRequest> should match
// service_traits::DataType< ::planner_msgs::planner_homing >
template<>
struct DataType< ::planner_msgs::planner_homingRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_homing >::value();
  }
  static const char* value(const ::planner_msgs::planner_homingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_homingResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_homing >
template<>
struct MD5Sum< ::planner_msgs::planner_homingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_homing >::value();
  }
  static const char* value(const ::planner_msgs::planner_homingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_homingResponse> should match
// service_traits::DataType< ::planner_msgs::planner_homing >
template<>
struct DataType< ::planner_msgs::planner_homingResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_homing >::value();
  }
  static const char* value(const ::planner_msgs::planner_homingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_HOMING_H
