// Generated by gencpp from file planner_msgs/planner_set_planning_modeRequest.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_SET_PLANNING_MODEREQUEST_H
#define PLANNER_MSGS_MESSAGE_PLANNER_SET_PLANNING_MODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct planner_set_planning_modeRequest_
{
  typedef planner_set_planning_modeRequest_<ContainerAllocator> Type;

  planner_set_planning_modeRequest_()
    : planning_mode(0)  {
    }
  planner_set_planning_modeRequest_(const ContainerAllocator& _alloc)
    : planning_mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _planning_mode_type;
  _planning_mode_type planning_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kManual)
  #undef kManual
#endif
#if defined(_WIN32) && defined(kAuto)
  #undef kAuto
#endif

  enum {
    kManual = 0,
    kAuto = 1,
  };


  typedef boost::shared_ptr< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct planner_set_planning_modeRequest_

typedef ::planner_msgs::planner_set_planning_modeRequest_<std::allocator<void> > planner_set_planning_modeRequest;

typedef boost::shared_ptr< ::planner_msgs::planner_set_planning_modeRequest > planner_set_planning_modeRequestPtr;
typedef boost::shared_ptr< ::planner_msgs::planner_set_planning_modeRequest const> planner_set_planning_modeRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.planning_mode == rhs.planning_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator1> & lhs, const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34a950857eb720557b21b9222e4269ae";
  }

  static const char* value(const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34a950857eb72055ULL;
  static const uint64_t static_value2 = 0x7b21b9222e4269aeULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/planner_set_planning_modeRequest";
  }

  static const char* value(const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Set the planning mode of the robot to use in planner.\n"
"int32 kManual = 0\n"
"int32 kAuto = 1\n"
"# Can only be used with one of above values. Check Params/BoundModeType for more details.\n"
"int32 planning_mode\n"
"\n"
;
  }

  static const char* value(const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.planning_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planner_set_planning_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::planner_set_planning_modeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "planning_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.planning_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_SET_PLANNING_MODEREQUEST_H
