// Generated by gencpp from file planner_msgs/planner_set_vel.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNER_SET_VEL_H
#define PLANNER_MSGS_MESSAGE_PLANNER_SET_VEL_H

#include <ros/service_traits.h>


#include <planner_msgs/planner_set_velRequest.h>
#include <planner_msgs/planner_set_velResponse.h>


namespace planner_msgs
{

struct planner_set_vel
{

typedef planner_set_velRequest Request;
typedef planner_set_velResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_set_vel
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planner_set_vel > {
  static const char* value()
  {
    return "f45ed41d58956a227be4845c1fe6bd6d";
  }

  static const char* value(const ::planner_msgs::planner_set_vel&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planner_set_vel > {
  static const char* value()
  {
    return "planner_msgs/planner_set_vel";
  }

  static const char* value(const ::planner_msgs::planner_set_vel&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planner_set_velRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planner_set_vel >
template<>
struct MD5Sum< ::planner_msgs::planner_set_velRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_set_vel >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_velRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_set_velRequest> should match
// service_traits::DataType< ::planner_msgs::planner_set_vel >
template<>
struct DataType< ::planner_msgs::planner_set_velRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_set_vel >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_velRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planner_set_velResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planner_set_vel >
template<>
struct MD5Sum< ::planner_msgs::planner_set_velResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planner_set_vel >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_velResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planner_set_velResponse> should match
// service_traits::DataType< ::planner_msgs::planner_set_vel >
template<>
struct DataType< ::planner_msgs::planner_set_velResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planner_set_vel >::value();
  }
  static const char* value(const ::planner_msgs::planner_set_velResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNER_SET_VEL_H
