// Generated by gencpp from file planner_msgs/RectangleShape.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_RECTANGLESHAPE_H
#define PLANNER_MSGS_MESSAGE_RECTANGLESHAPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct RectangleShape_
{
  typedef RectangleShape_<ContainerAllocator> Type;

  RectangleShape_()
    : center()
    , size()  {
    }
  RectangleShape_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::planner_msgs::RectangleShape_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::RectangleShape_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleShape_

typedef ::planner_msgs::RectangleShape_<std::allocator<void> > RectangleShape;

typedef boost::shared_ptr< ::planner_msgs::RectangleShape > RectangleShapePtr;
typedef boost::shared_ptr< ::planner_msgs::RectangleShape const> RectangleShapeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::RectangleShape_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::RectangleShape_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_msgs::RectangleShape_<ContainerAllocator1> & lhs, const ::planner_msgs::RectangleShape_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_msgs::RectangleShape_<ContainerAllocator1> & lhs, const ::planner_msgs::RectangleShape_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::RectangleShape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::RectangleShape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::RectangleShape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::RectangleShape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::RectangleShape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::RectangleShape_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::RectangleShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17746d0996c54d9b8b0dfe6f3cd0b588";
  }

  static const char* value(const ::planner_msgs::RectangleShape_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17746d0996c54d9bULL;
  static const uint64_t static_value2 = 0x8b0dfe6f3cd0b588ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::RectangleShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/RectangleShape";
  }

  static const char* value(const ::planner_msgs::RectangleShape_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::RectangleShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 center\n"
"geometry_msgs/Vector3 size\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::planner_msgs::RectangleShape_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::RectangleShape_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleShape_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::RectangleShape_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::RectangleShape_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_RECTANGLESHAPE_H
