// Generated by gencpp from file quadrotor_msgs/SetTakeoffLand.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_SETTAKEOFFLAND_H
#define QUADROTOR_MSGS_MESSAGE_SETTAKEOFFLAND_H

#include <ros/service_traits.h>


#include <quadrotor_msgs/SetTakeoffLandRequest.h>
#include <quadrotor_msgs/SetTakeoffLandResponse.h>


namespace quadrotor_msgs
{

struct SetTakeoffLand
{

typedef SetTakeoffLandRequest Request;
typedef SetTakeoffLandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTakeoffLand
} // namespace quadrotor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadrotor_msgs::SetTakeoffLand > {
  static const char* value()
  {
    return "34300860f54be45144752987f014ec7e";
  }

  static const char* value(const ::quadrotor_msgs::SetTakeoffLand&) { return value(); }
};

template<>
struct DataType< ::quadrotor_msgs::SetTakeoffLand > {
  static const char* value()
  {
    return "quadrotor_msgs/SetTakeoffLand";
  }

  static const char* value(const ::quadrotor_msgs::SetTakeoffLand&) { return value(); }
};


// service_traits::MD5Sum< ::quadrotor_msgs::SetTakeoffLandRequest> should match
// service_traits::MD5Sum< ::quadrotor_msgs::SetTakeoffLand >
template<>
struct MD5Sum< ::quadrotor_msgs::SetTakeoffLandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_msgs::SetTakeoffLand >::value();
  }
  static const char* value(const ::quadrotor_msgs::SetTakeoffLandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_msgs::SetTakeoffLandRequest> should match
// service_traits::DataType< ::quadrotor_msgs::SetTakeoffLand >
template<>
struct DataType< ::quadrotor_msgs::SetTakeoffLandRequest>
{
  static const char* value()
  {
    return DataType< ::quadrotor_msgs::SetTakeoffLand >::value();
  }
  static const char* value(const ::quadrotor_msgs::SetTakeoffLandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadrotor_msgs::SetTakeoffLandResponse> should match
// service_traits::MD5Sum< ::quadrotor_msgs::SetTakeoffLand >
template<>
struct MD5Sum< ::quadrotor_msgs::SetTakeoffLandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_msgs::SetTakeoffLand >::value();
  }
  static const char* value(const ::quadrotor_msgs::SetTakeoffLandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_msgs::SetTakeoffLandResponse> should match
// service_traits::DataType< ::quadrotor_msgs::SetTakeoffLand >
template<>
struct DataType< ::quadrotor_msgs::SetTakeoffLandResponse>
{
  static const char* value()
  {
    return DataType< ::quadrotor_msgs::SetTakeoffLand >::value();
  }
  static const char* value(const ::quadrotor_msgs::SetTakeoffLandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_SETTAKEOFFLAND_H
