// Generated by gencpp from file voxblox_msgs/FilePathRequest.msg
// DO NOT EDIT!


#ifndef VOXBLOX_MSGS_MESSAGE_FILEPATHREQUEST_H
#define VOXBLOX_MSGS_MESSAGE_FILEPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voxblox_msgs
{
template <class ContainerAllocator>
struct FilePathRequest_
{
  typedef FilePathRequest_<ContainerAllocator> Type;

  FilePathRequest_()
    : file_path()  {
    }
  FilePathRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;





  typedef boost::shared_ptr< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FilePathRequest_

typedef ::voxblox_msgs::FilePathRequest_<std::allocator<void> > FilePathRequest;

typedef boost::shared_ptr< ::voxblox_msgs::FilePathRequest > FilePathRequestPtr;
typedef boost::shared_ptr< ::voxblox_msgs::FilePathRequest const> FilePathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voxblox_msgs::FilePathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voxblox_msgs::FilePathRequest_<ContainerAllocator1> & lhs, const ::voxblox_msgs::FilePathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voxblox_msgs::FilePathRequest_<ContainerAllocator1> & lhs, const ::voxblox_msgs::FilePathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voxblox_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::voxblox_msgs::FilePathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1f82596372c52a5ULL;
  static const uint64_t static_value2 = 0x17e1fe32d1e998e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voxblox_msgs/FilePathRequest";
  }

  static const char* value(const ::voxblox_msgs::FilePathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
;
  }

  static const char* value(const ::voxblox_msgs::FilePathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FilePathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voxblox_msgs::FilePathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voxblox_msgs::FilePathRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOXBLOX_MSGS_MESSAGE_FILEPATHREQUEST_H
